server:
  port: 8080
database:
  dsn: "root:root@tcp(localhost:3306)/litedrive?charset=utf8mb4&parseTime=True"
jwt:
  secret: "wP3-sN6&gG4-lV8>gJ9)"
  expires: 1 # 小时
storage:
  root: "./storage"
  max_upload_size: "104857600"
  allowed_mime_types: "image/*,application/pdf,text/plain"